<a href="https://colab.research.google.com/github/sidharth-ds/python_Packages/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# numpy

In [ ]:
dir(np)

In [ ]:
np. __version__

'1.19.5'

# generating 1-D array

In [ ]:
x = np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
x.size

10

In [ ]:
x.itemsize

8

In [ ]:
x[1] = 20
x[4] = 5
x[5] = 9

In [ ]:
x

array([ 0., 20.,  0.,  0.,  5.,  9.,  0.,  0.,  0.,  0.])

In [ ]:
y = np.nonzero(x)
y

(array([1, 4, 5]),)

In [ ]:
type(x[1]),type(x[2])

(numpy.float64, numpy.float64)

# generating 2-D array

In [ ]:
i = np.zeros((10,4))
i

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
i.size

40

In [ ]:
i.itemsize    # memory of each item

8

In [ ]:
i.size*i.itemsize  # total memory

320

In [ ]:
i.shape

(10, 4)

In [ ]:
j = np.arange(10,45)
j

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44])

In [ ]:
k = np.arange(0,50)
k

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

* generating a range in Arithmetic progression:

---



In [ ]:
l = np.arange(5,51,5)
l

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [ ]:
m = np.arange(0,12)
m

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

* Reshaping a matrix (m)

---



In [ ]:
m.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
m.reshape(2,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [ ]:
m.reshape(6,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

* to access the Index of nonzero values:

---



In [ ]:
n = np.nonzero([3,5,0,8,0,2,1,0,8,9])
n

(array([0, 1, 3, 5, 6, 8, 9]),)

* Identity matrix

---



In [ ]:
o = np.eye(5)
o

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
o = np.eye(3)   
o

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# to generate random values

* random()

---



In [ ]:
p = np.random.random([3,4,2])    # 3-times, 4-rows, 2-column
p                              # values is between zero to one (always)

array([[[0.52737253, 0.97662815],
        [0.10451974, 0.67542188],
        [0.01619279, 0.42206056],
        [0.90114107, 0.89038408]],

       [[0.72455867, 0.86185899],
        [0.77358646, 0.90223842],
        [0.2712606 , 0.00170417],
        [0.81376686, 0.34692596]],

       [[0.3978718 , 0.79526681],
        [0.51867418, 0.21809166],
        [0.3760607 , 0.00609443],
        [0.34516   , 0.28034843]]])

In [ ]:
p = 10 * np.random.random([3,4,2])
p

array([[[2.94492931, 8.11556391],
        [7.72041768, 3.54508525],
        [4.76522467, 8.02496371],
        [5.01601686, 3.1920017 ]],

       [[5.40429092, 2.06363329],
        [6.72146715, 6.69597237],
        [7.17287602, 4.82815711],
        [8.51635926, 3.96520319]],

       [[1.43853452, 1.60511953],
        [8.84968204, 6.20277748],
        [3.52492385, 1.28315635],
        [0.77180208, 9.6000179 ]]])

In [ ]:
dir(np.random)

* randint()

---



In [ ]:
q = np.random.randint(20, size=(10,5))    # within 20,  10-rows, 5-columns
q

array([[14,  2, 15,  8, 13],
       [ 9,  2, 18,  2,  6],
       [14, 16, 15,  1, 15],
       [ 6,  0,  7,  2, 15],
       [ 9,  5,  8, 13,  6],
       [ 1,  9,  2, 17, 17],
       [ 0, 15,  9,  5, 13],
       [ 7, 11,  5,  0, 19],
       [ 3,  0,  7,  7, 19],
       [19, 13,  0, 12,  8]])

* Statistics in matrix

---



In [ ]:
q.max(), q.min(), q.mean(), q.sum()

(19, 0, 8.78, 439)

# changing the values

In [ ]:
e = np.ones((7,7))
e

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

* 0th row , 0th column = 0

---



In [ ]:
e[0,0] = 0
e

array([[0., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

* entire rows , 0th column = 0

---





In [ ]:
e[:,0] = 0
e

array([[0., 1., 1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1., 1., 1.]])

* entire rows , 6th column = 0

---




In [ ]:
e[:,6] = 0
e

array([[0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.]])

* 0th row , entire column = 0

---




In [ ]:
e[0,:] = 0
e

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.]])

* 6th row , entire column = 0

---




In [ ]:
e[6,:] = 0
e

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
f = np.ones((10,10))
f

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

* 2nd row to last-before row , 2nd column to last-before column = 0:

---



In [ ]:
f[1:-1,1:-1] = 0
f

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

# PADDING : used for image processing in deep learing

* Constant value is padded:

---



In [ ]:
g = np.arange(25).reshape(5,5)
h = np.pad(g,pad_width=1,mode='constant',constant_values=100)
h

array([[100, 100, 100, 100, 100, 100, 100],
       [100,   0,   1,   2,   3,   4, 100],
       [100,   5,   6,   7,   8,   9, 100],
       [100,  10,  11,  12,  13,  14, 100],
       [100,  15,  16,  17,  18,  19, 100],
       [100,  20,  21,  22,  23,  24, 100],
       [100, 100, 100, 100, 100, 100, 100]])

In [ ]:
g = np.arange(1,26).reshape(5,5)
h = np.pad(g,pad_width=2,mode='constant',constant_values=100)
h

array([[100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100,   1,   2,   3,   4,   5, 100, 100],
       [100, 100,   6,   7,   8,   9,  10, 100, 100],
       [100, 100,  11,  12,  13,  14,  15, 100, 100],
       [100, 100,  16,  17,  18,  19,  20, 100, 100],
       [100, 100,  21,  22,  23,  24,  25, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100]])

* edge rows, edge columns are padded:


---


In [ ]:
g = np.arange(1,26).reshape(5,5)
h = np.pad(g,pad_width=1,mode='edge')
h

array([[ 1,  1,  2,  3,  4,  5,  5],
       [ 1,  1,  2,  3,  4,  5,  5],
       [ 6,  6,  7,  8,  9, 10, 10],
       [11, 11, 12, 13, 14, 15, 15],
       [16, 16, 17, 18, 19, 20, 20],
       [21, 21, 22, 23, 24, 25, 25],
       [21, 21, 22, 23, 24, 25, 25]])

In [ ]:
g = np.arange(1,26).reshape(5,5)
h = np.pad(g,pad_width=2,mode='edge')
h

array([[ 1,  1,  1,  2,  3,  4,  5,  5,  5],
       [ 1,  1,  1,  2,  3,  4,  5,  5,  5],
       [ 1,  1,  1,  2,  3,  4,  5,  5,  5],
       [ 6,  6,  6,  7,  8,  9, 10, 10, 10],
       [11, 11, 11, 12, 13, 14, 15, 15, 15],
       [16, 16, 16, 17, 18, 19, 20, 20, 20],
       [21, 21, 21, 22, 23, 24, 25, 25, 25],
       [21, 21, 21, 22, 23, 24, 25, 25, 25],
       [21, 21, 21, 22, 23, 24, 25, 25, 25]])

* Maximum value of the row/column is padded:

---



In [ ]:
g = np.arange(1,26).reshape(5,5)
h = np.pad(g,pad_width=1,mode='maximum')
h

array([[25, 21, 22, 23, 24, 25, 25],
       [ 5,  1,  2,  3,  4,  5,  5],
       [10,  6,  7,  8,  9, 10, 10],
       [15, 11, 12, 13, 14, 15, 15],
       [20, 16, 17, 18, 19, 20, 20],
       [25, 21, 22, 23, 24, 25, 25],
       [25, 21, 22, 23, 24, 25, 25]])

* Minimum value of the row/column is padded:

---


In [ ]:
g = np.arange(1,26).reshape(5,5)
h = np.pad(g,pad_width=1,mode='minimum')
h

array([[ 1,  1,  2,  3,  4,  5,  1],
       [ 1,  1,  2,  3,  4,  5,  1],
       [ 6,  6,  7,  8,  9, 10,  6],
       [11, 11, 12, 13, 14, 15, 11],
       [16, 16, 17, 18, 19, 20, 16],
       [21, 21, 22, 23, 24, 25, 21],
       [ 1,  1,  2,  3,  4,  5,  1]])

* Mean value of the row/column is padded:

---


In [ ]:
g = np.arange(1,26).reshape(5,5)
h = np.pad(g,pad_width=1,mode='mean')
h

array([[13, 11, 12, 13, 14, 15, 13],
       [ 3,  1,  2,  3,  4,  5,  3],
       [ 8,  6,  7,  8,  9, 10,  8],
       [13, 11, 12, 13, 14, 15, 13],
       [18, 16, 17, 18, 19, 20, 18],
       [23, 21, 22, 23, 24, 25, 23],
       [13, 11, 12, 13, 14, 15, 13]])

* Median value of the row/column is padded:

---


In [ ]:
g = np.arange(1,26).reshape(5,5)
h = np.pad(g,pad_width=1,mode='median')
h

array([[13, 11, 12, 13, 14, 15, 13],
       [ 3,  1,  2,  3,  4,  5,  3],
       [ 8,  6,  7,  8,  9, 10,  8],
       [13, 11, 12, 13, 14, 15, 13],
       [18, 16, 17, 18, 19, 20, 18],
       [23, 21, 22, 23, 24, 25, 23],
       [13, 11, 12, 13, 14, 15, 13]])

* Reflection based on 0th row and 0th column (excluding 0th row and 0th column)

---



In [ ]:
g = np.arange(1,26).reshape(5,5)
h = np.pad(g,pad_width=1,mode='reflect')
h

array([[ 7,  6,  7,  8,  9, 10,  9],
       [ 2,  1,  2,  3,  4,  5,  4],
       [ 7,  6,  7,  8,  9, 10,  9],
       [12, 11, 12, 13, 14, 15, 14],
       [17, 16, 17, 18, 19, 20, 19],
       [22, 21, 22, 23, 24, 25, 24],
       [17, 16, 17, 18, 19, 20, 19]])

In [ ]:
g = np.arange(1,26).reshape(5,5)
h = np.pad(g,pad_width=5,mode='reflect')
h

array([[19, 20, 19, 18, 17, 16, 17, 18, 19, 20, 19, 18, 17, 16, 17],
       [24, 25, 24, 23, 22, 21, 22, 23, 24, 25, 24, 23, 22, 21, 22],
       [19, 20, 19, 18, 17, 16, 17, 18, 19, 20, 19, 18, 17, 16, 17],
       [14, 15, 14, 13, 12, 11, 12, 13, 14, 15, 14, 13, 12, 11, 12],
       [ 9, 10,  9,  8,  7,  6,  7,  8,  9, 10,  9,  8,  7,  6,  7],
       [ 4,  5,  4,  3,  2,  1,  2,  3,  4,  5,  4,  3,  2,  1,  2],
       [ 9, 10,  9,  8,  7,  6,  7,  8,  9, 10,  9,  8,  7,  6,  7],
       [14, 15, 14, 13, 12, 11, 12, 13, 14, 15, 14, 13, 12, 11, 12],
       [19, 20, 19, 18, 17, 16, 17, 18, 19, 20, 19, 18, 17, 16, 17],
       [24, 25, 24, 23, 22, 21, 22, 23, 24, 25, 24, 23, 22, 21, 22],
       [19, 20, 19, 18, 17, 16, 17, 18, 19, 20, 19, 18, 17, 16, 17],
       [14, 15, 14, 13, 12, 11, 12, 13, 14, 15, 14, 13, 12, 11, 12],
       [ 9, 10,  9,  8,  7,  6,  7,  8,  9, 10,  9,  8,  7,  6,  7],
       [ 4,  5,  4,  3,  2,  1,  2,  3,  4,  5,  4,  3,  2,  1,  2],
       [ 9, 10,  9,  8,  7,  6,  7

* Reflection based on 0th row and 0th column (including 0th row and 0th column)

---

In [ ]:
g = np.arange(1,26).reshape(5,5)
h = np.pad(g,pad_width=1,mode='symmetric')
h

array([[ 1,  1,  2,  3,  4,  5,  5],
       [ 1,  1,  2,  3,  4,  5,  5],
       [ 6,  6,  7,  8,  9, 10, 10],
       [11, 11, 12, 13, 14, 15, 15],
       [16, 16, 17, 18, 19, 20, 20],
       [21, 21, 22, 23, 24, 25, 25],
       [21, 21, 22, 23, 24, 25, 25]])

In [ ]:
g = np.arange(1,26).reshape(5,5)
h = np.pad(g,pad_width=5,mode='symmetric')
h

array([[25, 24, 23, 22, 21, 21, 22, 23, 24, 25, 25, 24, 23, 22, 21],
       [20, 19, 18, 17, 16, 16, 17, 18, 19, 20, 20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11, 11, 12, 13, 14, 15, 15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6,  6,  7,  8,  9, 10, 10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1,  1,  2,  3,  4,  5,  5,  4,  3,  2,  1],
       [ 5,  4,  3,  2,  1,  1,  2,  3,  4,  5,  5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6,  6,  7,  8,  9, 10, 10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11, 11, 12, 13, 14, 15, 15, 14, 13, 12, 11],
       [20, 19, 18, 17, 16, 16, 17, 18, 19, 20, 20, 19, 18, 17, 16],
       [25, 24, 23, 22, 21, 21, 22, 23, 24, 25, 25, 24, 23, 22, 21],
       [25, 24, 23, 22, 21, 21, 22, 23, 24, 25, 25, 24, 23, 22, 21],
       [20, 19, 18, 17, 16, 16, 17, 18, 19, 20, 20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11, 11, 12, 13, 14, 15, 15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6,  6,  7,  8,  9, 10, 10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1,  1,  2

* Reflection based on 0th row and 0th column (from the last row and last column) (mirror image)

---

In [ ]:
g = np.arange(1,26).reshape(5,5)
h = np.pad(g,pad_width=1,mode='wrap')
h

array([[25, 21, 22, 23, 24, 25, 21],
       [ 5,  1,  2,  3,  4,  5,  1],
       [10,  6,  7,  8,  9, 10,  6],
       [15, 11, 12, 13, 14, 15, 11],
       [20, 16, 17, 18, 19, 20, 16],
       [25, 21, 22, 23, 24, 25, 21],
       [ 5,  1,  2,  3,  4,  5,  1]])

In [ ]:
g = np.arange(1,26).reshape(5,5)
h = np.pad(g,pad_width=5,mode='wrap')
h

array([[ 1,  2,  3,  4,  5,  1,  2,  3,  4,  5,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10,  6,  7,  8,  9, 10,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 11, 12, 13, 14, 15, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 16, 17, 18, 19, 20, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 21, 22, 23, 24, 25, 21, 22, 23, 24, 25],
       [ 1,  2,  3,  4,  5,  1,  2,  3,  4,  5,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10,  6,  7,  8,  9, 10,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 11, 12, 13, 14, 15, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 16, 17, 18, 19, 20, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 21, 22, 23, 24, 25, 21, 22, 23, 24, 25],
       [ 1,  2,  3,  4,  5,  1,  2,  3,  4,  5,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10,  6,  7,  8,  9, 10,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 11, 12, 13, 14, 15, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 16, 17, 18, 19, 20, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 21, 22